// Package routes provides the online account authentication and session
// management endpoints.
//
// Purpose:
//
// This package handles the server-side lifecycle of user authentication.
// It provides registration, pre-login password-salt retrieval, password
// verification, access-token issuance, refresh-token rotation, and logout
// operations for individual devices or all devices belonging to a user.
//
// Password verification is performed against a server-side HMAC-derived
// verifier, while access and refresh credentials use separate token
// mechanisms managed by the middleware and database layers.
//
// Exports:
//
//   - Register — Creates a new online user, registers the user's device,
//     generates the initial access and refresh tokens, and persists the
//     refresh-token record.
//   - PreLogin — Returns the password salt associated with an email address
//     without revealing whether the account exists.
//   - Login — Verifies user credentials and device ownership, applies
//     progressive lockout rules, and creates a new authenticated session.
//   - Refresh — Atomically consumes a valid refresh token and issues a new
//     access token together with a rotated refresh token.
//   - Logout — Invalidates all refresh tokens associated with the current
//     authenticated user and device.
//   - LogoutAll — Invalidates all refresh tokens belonging to the current
//     authenticated user.
//
// Key design decisions:
//
// Password verification uses a client-derived password representation rather
// than receiving the user's plaintext password. During registration and login,
// the server combines that representation with a server-side pepper using
// HMAC-SHA256 and stores the resulting verifier instead of the original
// password-derived value.
//
// The server never returns account-existence information from PreLogin.
// When an email is not registered, a cryptographically random dummy salt is
// returned so that the endpoint does not directly reveal whether the account
// exists.
//
// Access and refresh credentials are deliberately separated. Access tokens
// are short-lived JWTs generated by the authentication middleware, while
// refresh tokens consist of a random UUID identifier and an HMAC-derived
// signature stored in the database.
//
// Refresh tokens are rotated on every successful refresh. The currently used
// refresh-token record is deleted before a new refresh token is created,
// preventing the same token from being reused after successful rotation.
//
// Refresh tokens are additionally bound to both the authenticated user and
// device. This allows Logout to invalidate the current device session without
// affecting sessions on other devices, while LogoutAll removes all refresh
// credentials for the account.
//
// Failed password attempts are tracked per user. Every fifth consecutive
// failed attempt creates a temporary lockout, and a successful login resets
// the failed-attempt counter.
//
// Device identity is verified during login by requiring a device identifier
// that belongs to the authenticated user. The same device identifier is then
// embedded into the issued access token and stored with the refresh token.
//
// Authentication-sensitive operations use bounded database contexts so that
// MongoDB operations cannot block a request indefinitely.
//
// User-controlled account information is never accepted as the authoritative
// initial storage quota. Server-owned quota state is initialized explicitly
// during registration.
//
// Secrets such as the password pepper are retrieved from the configuration
// layer rather than embedded directly in the authentication routes.
//
// # Authentication flow
//
// Registration creates the user and device records and immediately establishes
// an authenticated session.
//
// Login first resolves the account and device, checks the current lockout
// state, verifies the password-derived value using constant-time comparison,
// and issues fresh access and refresh credentials.
//
// Refresh consumes the existing refresh credential and rotates it into a new
// credential pair.
//
// Logout removes refresh credentials for the current device, while LogoutAll
// removes refresh credentials for every device belonging to the user.
//
// Dependencies:
//
//   - github.com/gofiber/fiber/v3 — HTTP request handling and response
//     generation.
//   - github.com/gofiber/fiber/v3/log — Authentication and database error
//     logging.
//   - go.mongodb.org/mongo-driver/v2 — Persistence of users, devices, and
//     refresh-token records.
//   - github.com/google/uuid — Device identifiers and refresh-token UUID
//     generation/parsing.
//   - crypto/hmac — Server-side HMAC computation for password verifiers and
//     refresh-token signatures.
//   - crypto/sha256 — SHA-256 digest used by the HMAC constructions.
//   - crypto/rand — Cryptographically secure generation of dummy password
//     salts.
//   - crypto/subtle — Constant-time comparison of password verifier values.
//   - encoding/base64 — Encoding binary password and key material for HTTP
//     responses.
//   - llava-server/config — Retrieval of server-side authentication secrets.
//   - llava-server/middleware — Validation, token generation, and standardized
//     HTTP error responses.
//   - llava-server/models — User, device, request, and refresh-token data
//     structures.
package routes

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"llava-server/config"
	"llava-server/middleware"
	"llava-server/models"
	"strings"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/log"
	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

func (h *Handler) Register(c fiber.Ctx) error {
	registerRequest := new(models.RegisterRequest)

	if err := c.Bind().Body(registerRequest); err != nil {
		return middleware.BadRequest("Couldnt read body data")
	}

	if err := h.Validator.Struct(registerRequest); err != nil {
		return middleware.BadRequest("Wrong user struct was sent")
	}

	pepperSecret, err := config.GetPepperSecret()
	if err != nil {
		log.Errorf("register: failed to get pepper secret: %v", err)
		return middleware.Internal("Internal server configuration error")
	}

	localUser := registerRequest.LocalUserModel

	mac := hmac.New(sha256.New, pepperSecret)
	mac.Write([]byte(localUser.PasswordHash))
	passwordVerifier := mac.Sum(nil)

	user := &models.User{
		ID:               localUser.ID,
		Email:            localUser.Email,
		EmailVerified:    localUser.EmailVerified,
		PasswordVerifier: passwordVerifier,
		PasswordSalt:     localUser.PasswordSalt,
		MasterKeyEnc:     localUser.MasterKeyEnc,
		MasterKeyNonce:   localUser.MasterKeyNonce,
		KekSalt:          localUser.KekSalt,
		ArgonParams:      localUser.ArgonParams,
		// Storage accounting is server-owned. Never accept a starting balance
		// from the registering client: it could otherwise bypass the quota.
		QuotaUsed:      0,
		FailedAttempts: 0,
		LockoutUntil:   nil,

		CreatedAt: time.Now().UnixMilli(),
		LastLogin: time.Now().UnixMilli(),
	}

	device := registerRequest.Device

	ctx, cancel := context.WithTimeout(
		context.Background(),
		5*time.Second,
	)
	defer cancel()

	usersColl := h.DB.Collection("users_data")

	opts := options.FindOne().SetProjection(bson.M{"_id": 1})

	err = usersColl.FindOne(
		ctx,
		bson.M{"email": user.Email},
		opts,
	).Err()

	if err == nil {
		return middleware.Conflict("this email exists")
	}

	if err != mongo.ErrNoDocuments {
		log.Errorf("register: email lookup failed: %v", err)
		return middleware.Internal("database error")
	}

	res, err := usersColl.InsertOne(ctx, user)
	if err != nil {
		log.Errorf("register: insert user failed: %v", err)
		return middleware.Internal("Couldnt insert data to collection")
	}

	userID, ok := res.InsertedID.(bson.ObjectID)
	if !ok {
		log.Errorf("register: inserted ID is not ObjectID")
		return middleware.Internal("database error")
	}

	devicesColl := h.DB.Collection("devices")

	device.UserID = userID
	device.CreatedAt = time.Now().UnixMilli()
	device.LastSeen = time.Now().UnixMilli()

	_, err = devicesColl.InsertOne(ctx, device)
	if err != nil {
		log.Errorf("register: insert device failed: %v", err)
		return middleware.Internal("Couldnt insert data to collection")
	}

	accessToken, err := middleware.GenerateAccessToken(
		device.DeviceID,
		userID.Hex(),
	)
	if err != nil {
		return middleware.Internal("Couldnt generate access token")
	}

	jti, signature, err := middleware.GenerateRefreshToken()
	if err != nil {
		return middleware.Internal("Couldnt generate refresh token")
	}

	jwtColl := h.DB.Collection("jwt")

	refreshInsert := &models.RefreshToken{
		CreatedAt: time.Now().UnixMilli(),
		ExpiresAt: time.Now().Add(30 * 24 * time.Hour).UnixMilli(),
		JTI:       jti.String(),
		UserID:    userID,
		DeviceID:  device.DeviceID,
		TokenHash: signature,
	}

	_, err = jwtColl.InsertOne(ctx, refreshInsert)
	if err != nil {
		log.Errorf("register: insert refresh token failed: %v", err)
		return middleware.Internal("Couldnt insert data to collection")
	}

	return c.Status(fiber.StatusCreated).JSON(fiber.Map{
		"access_token":  accessToken,
		"refresh_token": jti.String() + "." + signature,
		"user_id":       userID.Hex(),
	})
}

type PreLoginRequest struct {
	Email string `json:"email"  validate:"required,email"`
}

func generateDummySalt() []byte {
	salt := make([]byte, 16)
	rand.Read(salt)
	return salt
}
func (h *Handler) PreLogin(c fiber.Ctx) error {
	request := new(PreLoginRequest)

	if err := c.Bind().Body(request); err != nil {
		return middleware.BadRequest("no body")
	}

	if err := h.Validator.Struct(request); err != nil {
		return middleware.BadRequest("Wrong pre login struct was sent")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	usersColl := h.DB.Collection("users_data")

	var user models.User

	err := usersColl.FindOne(
		ctx,
		bson.M{"email": request.Email},
	).Decode(&user)

	if err != nil {
		// Nie ujawniamy, czy email istnieje.
		return c.Status(fiber.StatusOK).JSON(fiber.Map{
			"password_salt": base64.RawStdEncoding.EncodeToString(generateDummySalt()),
		})
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"password_salt": user.PasswordSalt,
	})
}

type LoginRequest struct {
	Email        string    `json:"email"  validate:"required,email"`
	PasswordHash string    `json:"password_hash" validate:"required"`
	DeviceID     uuid.UUID `json:"device_id"  validate:"required"`
}

func (h *Handler) Login(c fiber.Ctx) error {
	var request = new(LoginRequest)

	err := c.Bind().Body(request)
	if err != nil {
		return middleware.BadRequest("no body")
	}

	if err := h.Validator.Struct(request); err != nil {
		return middleware.BadRequest("Wrong user struct was sent")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	usersColl := h.DB.Collection("users_data")

	res := usersColl.FindOne(
		ctx,
		bson.M{"email": request.Email},
	)

	var user models.User

	if err := res.Decode(&user); err != nil {
		return middleware.Unauthorized("invalid_credentials")
	}

	now := time.Now().UnixMilli()

	if user.LockoutUntil != nil && now < *user.LockoutUntil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"timeout": *user.LockoutUntil,
		})
	}

	pepperSecret, err := config.GetPepperSecret()
	if err != nil {
		log.Errorf("register: failed to get pepper secret: %v", err)
		return middleware.Internal("Internal server configuration error")
	}

	mac := hmac.New(sha256.New, pepperSecret)
	mac.Write([]byte(request.PasswordHash))
	passwordVerifier := mac.Sum(nil)

	if subtle.ConstantTimeCompare(
		[]byte(user.PasswordVerifier),
		[]byte(passwordVerifier),
	) == 1 {

		deviceColl := h.DB.Collection("devices")

		var device models.Device

		err := deviceColl.FindOne(
			ctx,
			bson.M{
				"user_id":   user.ID,
				"device_id": request.DeviceID,
			},
		).Decode(&device)

		if errors.Is(err, mongo.ErrNoDocuments) {
			device = models.Device{
				UserID:    *user.ID,
				DeviceID:  request.DeviceID,
				CreatedAt: time.Now().UnixMilli(),
				LastSeen:  time.Now().UnixMilli(),
			}

			if _, err := deviceColl.InsertOne(ctx, device); err != nil {
				log.Errorf("login: failed to register device: %v", err)
				return middleware.Internal("Couldnt register device")
			}
		} else if err != nil {
			log.Errorf("login: failed to find device: %v", err)
			return middleware.Internal("Couldnt load device")
		} else {
			_, err := deviceColl.UpdateOne(
				ctx,
				bson.M{
					"user_id":   user.ID,
					"device_id": request.DeviceID,
				},
				bson.M{
					"$set": bson.M{
						"last_seen": time.Now().UnixMilli(),
					},
				},
			)

			if err != nil {
				log.Errorf("login: failed to update device last seen: %v", err)
				return middleware.Internal("Couldnt update device")
			}
		}

		accessToken, err := middleware.GenerateAccessToken(
			device.DeviceID,
			user.ID.Hex(),
		)

		if err != nil {
			return middleware.Internal("Couldnt generate Access Token")
		}

		jti, signature, err := middleware.GenerateRefreshToken()

		if err != nil {
			return middleware.Internal("Couldnt generate Refresh Token")
		}

		jwtColl := h.DB.Collection("jwt")

		refreshInsert := new(models.RefreshToken)

		refreshInsert.CreatedAt = time.Now().UnixMilli()
		refreshInsert.ExpiresAt = time.Now().Add(30 * 24 * time.Hour).UnixMilli()
		refreshInsert.JTI = jti.String()
		refreshInsert.UserID = *user.ID
		refreshInsert.DeviceID = device.DeviceID
		refreshInsert.TokenHash = signature

		if _, err = jwtColl.InsertOne(ctx, refreshInsert); err != nil {
			return middleware.Internal("couldn't save refresh token")
		}

		usersColl.UpdateOne(
			ctx,
			bson.M{"_id": user.ID},
			bson.M{
				"$set": bson.M{
					"last_login":      time.Now().UnixMilli(),
					"failed_attempts": 0,
				},
			},
		)

		return c.Status(fiber.StatusOK).JSON(fiber.Map{
			"access_token":     accessToken,
			"refresh_token":    jti.String() + "." + signature,
			"user_id":          refreshInsert.UserID.Hex(),
			"master_key_enc":   base64.StdEncoding.EncodeToString(user.MasterKeyEnc),
			"master_key_nonce": base64.StdEncoding.EncodeToString(user.MasterKeyNonce),
			"kek_salt":         user.KekSalt,
			"params":           user.ArgonParams,
		})

	} else {

		failedAttempts := user.FailedAttempts + 1

		if _, err := usersColl.UpdateOne(
			ctx,
			bson.M{"_id": user.ID},
			bson.M{
				"$set": bson.M{
					"failed_attempts": failedAttempts,
				},
			},
		); err != nil {
			return middleware.Unauthorized("wrong password")
		}

		if (user.FailedAttempts+1)%5 == 0 {
			timeoutUntil := time.Now().Add(30 * time.Second).UnixMilli()

			_, err = usersColl.UpdateOne(
				ctx,
				bson.M{"_id": user.ID},
				bson.M{
					"$set": bson.M{
						"lockout_until": timeoutUntil,
					},
				},
			)

			if err != nil {
				return middleware.Internal("Internal Error")
			}

			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"timeout": timeoutUntil,
			})
		}

		return middleware.Unauthorized("wrong password")
	}
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

func (h *Handler) Refresh(c fiber.Ctx) error {
	req := new(RefreshRequest)
	if err := c.Bind().Body(req); err != nil {
		return middleware.BadRequest("invalid refresh token")
	}

	parts := strings.SplitN(req.RefreshToken, ".", 2)
	if len(parts) != 2 {
		return middleware.Unauthorized("invalid_refresh_token")
	}
	jtiParsed, err := uuid.Parse(parts[0])
	if err != nil {
		return middleware.Unauthorized("invalid_refresh_token")
	}
	signature := parts[1]

	jwtColl := h.DB.Collection("jwt")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	now := time.Now().UnixMilli()
	res := jwtColl.FindOneAndDelete(ctx, bson.M{
		"jti":        jtiParsed.String(),
		"token_hash": signature,
		"expires_at": bson.M{"$gt": now},
	})

	var refresh models.RefreshToken
	if err := res.Decode(&refresh); err != nil {
		if err != mongo.ErrNoDocuments {
			return middleware.Internal("database error")
		}

		expiredRes := jwtColl.FindOneAndDelete(ctx, bson.M{
			"jti":        jtiParsed.String(),
			"token_hash": signature,
			"expires_at": bson.M{"$lte": now},
		})
		if expiredRes.Err() == nil {
			return middleware.Unauthorized("session_expired")
		}
		if expiredRes.Err() != mongo.ErrNoDocuments {
			return middleware.Internal("database error")
		}
		return middleware.Unauthorized("invalid_refresh_token")
	}

	accessToken, err := middleware.GenerateAccessToken(refresh.DeviceID, refresh.UserID.Hex())
	if err != nil {
		return middleware.Internal("Couldnt generate new access token")
	}
	jtis, signature, err := middleware.GenerateRefreshToken()
	if err != nil {
		return middleware.Internal("Couldnt generate new refresh token")
	}

	var newRefresh models.RefreshToken
	newRefresh.CreatedAt = time.Now().UnixMilli()
	newRefresh.ExpiresAt = time.Now().Add(30 * 24 * time.Hour).UnixMilli()
	newRefresh.UserID = refresh.UserID
	newRefresh.DeviceID = refresh.DeviceID
	newRefresh.JTI = jtis.String()
	newRefresh.TokenHash = signature
	_, err = jwtColl.InsertOne(ctx, newRefresh)
	if err != nil {
		return middleware.Internal("Couldnt insert new refresh token")
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"access_token":  accessToken,
		"refresh_token": jtis.String() + "." + signature,
	})

}

func (h *Handler) Logout(c fiber.Ctx) error {
	userIdStr, ok := c.Locals("userID").(string)
	if !ok {
		return middleware.BadRequest("user not attached")
	}
	deviceId, ok := c.Locals("deviceID").(uuid.UUID)
	if !ok {
		return middleware.BadRequest("device not attached")
	}
	userId, err := bson.ObjectIDFromHex(userIdStr)
	if err != nil {
		return middleware.BadRequest("invalid user id")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	jwtColl := h.DB.Collection("jwt")
	_, err = jwtColl.DeleteMany(ctx, bson.M{"user_id": userId, "device_id": deviceId})
	if err != nil {
		return middleware.Internal("Couldnt delete refresh token")
	}
	return c.SendStatus(fiber.StatusNoContent)

}

func (h *Handler) LogoutAll(c fiber.Ctx) error {
	userIdStr, ok := c.Locals("userID").(string)
	if !ok {
		return middleware.BadRequest("user not attached")
	}

	userId, err := bson.ObjectIDFromHex(userIdStr)
	if err != nil {
		return middleware.BadRequest("invalid user id")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	jwtColl := h.DB.Collection("jwt")
	_, err = jwtColl.DeleteMany(ctx, bson.M{"user_id": userId})
	if err != nil {
		return middleware.Internal("Couldnt delete refresh tokens")
	}
	return c.SendStatus(fiber.StatusNoContent)
}
